# Generated by Django 2.2.5 on 2019-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[{'ACTION', 'A'}, {'DRAMA', 'D'}, {'COMEDY', 'C'}, {'ROMANCE', 'R'}], max_length=1)),
                ('language', models.CharField(choices=[{'EN', 'ENGLISH'}, {'GR', 'GERMAN'}, {'HN', 'HINDI'}], max_length=1)),
                ('status', models.CharField(choices=[{'RA', 'RECENTLY ADDED'}, {'MOST WATCHED', 'MW'}, {'TOP RATED', 'TR'}], max_length=1)),
                ('year_of_production', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
