# Generated by Django 2.2.5 on 2019-09-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190930_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieLinks',
            new_name='MovieLink',
        ),
    ]
