# Generated by Django 2.2.5 on 2019-09-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190930_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('HN', 'HINDI'), ('GR', 'GERMAN')], max_length=2),
        ),
    ]
