# Generated by Django 2.2.5 on 2019-09-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20190930_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI'), ('german', 'GERMAN')], max_length=10),
        ),
    ]
