# Generated by Django 2.2.5 on 2019-09-30 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 16, 45, 13, 136629, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
